# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "Storia"
pageRef = "posts/history"
weight = 1

[[main]]
name = "Valori"
pageRef = "posts/values"
weight = 2

[[main]]
name = "Palmares"
pageRef = "posts/palmares"
weight = 3

[[main]]
name = "Senior"
pageRef = "posts/championship/20242025"
weight = 30

[[main]]
name = "Allenamenti"
parent = "Senior"
pageRef = "training"
weight = 10

[[main]]
name = "Campionato 2024/2025"
parent = "Senior"
pageRef = "posts/championship/20242025"
weight = 11

[[main]]
name = "Campionato 2023/2024"
parent = "Senior"
pageRef = "posts/archive/championship/20232024"
weight = 20

# [[main]]
# name = "Under"
# pageRef = "posts/under"
# weight = 30

[[main]]
name = "Shop"
url = "https://clubshop.macron.com/ravenna/saviors-social-rugby-cesena"
weight = 40

[[main]]
name = "Old"
pageRef = "posts/old"
weight = 50

# [[main]]
# name = " Allenamenti"
# parent = "Under"
# pageRef = "training-under"
# weight = 10

# [[main]]
# name = " Calendario"
# parent = "Under"
# pageRef = "posts/calendar-under"
# weight = 20

[[main]]
name = "Staff"
pageRef = "posts/staff"
weight = 90

[[main]]
name = "Progetto Savio"
url = "https://progettosavio.saviorssocialrugby.it/"
weight = 100

[[main]]
name = "Contatti"
pageRef = "contact"
weight = 110

[[main]]
identifier = "instagram"
pre = "instagram"
url = "https://www.instagram.com/saviors_social_rugby"
weight = 120

[[main]]
identifier = "facebook"
pre = "facebook"
url = "https://www.facebook.com/saviorssocialrugby"
weight = 130

[[main]]
identifier = "whatsapp"
pre = "whatsapp"
url = "https://wa.me/+393297956230"
weight = 140

# [[main]]
# name = "sub-menu 1"
# parent = "Under"
# pageRef = "samples"
# weight = 30

# [[subnavigation]]
# name = "An interesting topic"
# pageRef = "tags/interesting-topic"
# weight = 10

# [[subnavigation]]
# name = "My Awesome Category"
# pre = "github"
# pageRef = "categories/awesome"
# weight = 20

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
# name = "Tags"
# pageRef = "tags"
# weight = 10

# [[footer]]
# name = "Categories"
# pageRef = "categories"
# weight = 20

[[footer]]
name = " Instagram"
url = "https://www.instagram.com/saviors_social_rugby"

[[footer]]
name = " Whatsapp"
url = "https://wa.me/+393297956230"

[[footer]]
name = " Facebook"
url = "https://www.facebook.com/saviorssocialrugby"

[[footer]]
name = " E-mail"
url = "mailto:info@saviorssocialrugby.it"

[[footer]]
name = "Codice di condotta"
url = "/documents/codice_di_condotta.pdf"
